name: Build & Deploy container image

on:
  schedule:
    - cron: '0 0 * * *' # everyday at midnight UTC
  pull_request:
    branches: master
  push:
    branches: master
    tags: '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base-image: [stable]
        destination-image: [nginx-fpm-alpine, pdo]
    name: ${{ matrix.destination-image }} image / ${{ matrix.base-image }} release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: (github.ref != 'refs/heads/master' && github.event_name != 'pull_request') || github.event_name == 'schedule'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Docker Build
        run: ./buildx.sh ${{ github.event_name }} ${{ matrix.destination-image }} ${{ matrix.base-image }}
